if (SMS_TEACHER_LAYOUT.init("classes")) {
(function(){
  var params=new URLSearchParams(window.location.search), classId=params.get("id"), term=params.get("term")||"S1";
  var myClasses=SMS_TEACHER_LAYOUT.getMyClasses(), cls=myClasses.find(function(c){return c.id===classId;});
  var root=document.getElementById("page-content");
  if(!cls){root.innerHTML=SMS_UI.pageHeader({title:"Class not found",subtitle:"This class is not assigned to your teacher account.",breadcrumb:["Teacher","My Classes"]})+'<div class="card"><div class="card-body">'+SMS_UI.emptyState({icon:"fa-lock",title:"Class unavailable",message:"Return to My Classes and choose one of your assigned classes."})+'<div style="text-align:center"><a class="btn btn-primary" href="./classes.html">Back to My Classes</a></div></div></div>';return;}
  var branchId=SMS_AUTH.getBranchId(), teacher=SMS_TEACHER_LAYOUT.getMyTeacher();
  var canGrades=SMS_AUTH.hasTeacherPermission("grades.view"), canAttendance=SMS_AUTH.hasTeacherPermission("attendance.view"), canGuardian=SMS_AUTH.hasTeacherPermission("students.guardian_contact"), canHealth=SMS_AUTH.hasTeacherPermission("students.health_alerts");
  Promise.all([SMS_API.getStudents(branchId),SMS_API.getAssignments(),SMS_API.getGrades(),SMS_API.getAnnouncements(branchId),SMS_API.getDocuments(branchId),SMS_API.getPhotoAlbums(branchId),SMS_API.getAttendance({})]).then(function(res){
    var students=res[0].filter(function(s){return (cls.studentIds||[]).includes(s.id);}), assignments=res[1].filter(function(a){return a.classId===cls.id;}), grades=res[2].filter(function(g){return g.classId===cls.id;}), announcements=res[3], docs=res[4], albums=res[5], attendance=res[6].filter(function(a){return a.classId===cls.id;});
    function year(){return SMS_SCHOOL_YEARS.find(function(y){return y.schoolId===SMS_AUTH.getSchoolId()&&y.isCurrent;});}
    function termData(){var y=year(); if(!y||!y.semesters||!y.semesters.length)return null;return y.semesters[term==="S2"?1:0]||y.semesters[0];}
    function inTerm(date){var t=termData(); return !t||!date||(date>=t.start&&date<=t.end);}
    function termAssignments(){return assignments.filter(function(a){return inTerm(a.dueDate);}).sort(function(a,b){return String(a.dueDate).localeCompare(String(b.dueDate));});}
    function average(){if(!canGrades||!grades.length)return null;var pct=grades.reduce(function(n,g){return n+(Number(g.score)/Number(g.totalPoints))*100;},0)/grades.length;return Math.round(pct);}
    function hrefForTerm(base){return base+(base.indexOf('?')>=0?'&':'?')+'term='+term;}
    function render(){
      var ta=termAssignments(), avg=average(), t=termData(), pageTitle=cls.name;
      root.innerHTML=SMS_UI.pageHeader({title:pageTitle,subtitle:"Class Home · "+(t?t.name:(term==="S2"?"Semester 2":"Semester 1")),breadcrumb:["Teacher","My Classes",cls.name],actions:[{label:"Back to Classes",icon:"fa-arrow-left",id:"back-classes"}]})+
      '<div class="term-tabs"><button class="term-tab '+(term==='S1'?'active':'')+'" data-term="S1">Semester 1</button><button class="term-tab '+(term==='S2'?'active':'')+'" data-term="S2">Semester 2</button></div>'+
      '<section class="class-workspace-hero"><div class="class-hero-top"><div><div class="class-hero-kicker">'+SMS_UI.esc(cls.subject||'Class')+'</div><div class="class-hero-name">'+SMS_UI.esc(cls.name)+'</div><div class="class-hero-sub">'+SMS_UI.esc(cls.grade||'')+' · '+students.length+' students</div></div>'+SMS_UI.badge(cls.semester||'Full Year','primary')+'</div><div class="class-hero-chips"><span class="class-hero-chip"><i class="fa-solid fa-door-open"></i>'+SMS_UI.esc(cls.room||'Room not set')+'</span><span class="class-hero-chip"><i class="fa-solid fa-clock"></i>'+SMS_UI.esc(cls.schedule||'Schedule not set')+'</span><span class="class-hero-chip"><i class="fa-solid fa-chalkboard-user"></i>'+SMS_UI.esc(cls.teacherName||teacher.fullName)+'</span></div></section>'+
      '<div class="class-subtabs"><button class="class-subtab active" data-class-tab="overview"><i class="fa-solid fa-house"></i>Class Home</button><button class="class-subtab" data-class-tab="news"><i class="fa-solid fa-newspaper"></i>News</button><button class="class-subtab" data-class-tab="calendar"><i class="fa-solid fa-calendar-days"></i>Calendar</button><button class="class-subtab" data-class-tab="documents"><i class="fa-solid fa-file-lines"></i>Documents</button><button class="class-subtab" data-class-tab="photos"><i class="fa-solid fa-camera"></i>Photos</button><button class="class-subtab" data-class-tab="roster"><i class="fa-solid fa-users"></i>Students</button></div><div id="class-tab-panel" class="class-tab-panel"></div>';
      document.getElementById('back-classes').onclick=function(){window.location.href='./classes.html?term='+term;};
      document.querySelectorAll('[data-term]').forEach(function(btn){btn.onclick=function(){term=btn.dataset.term;var u=new URL(window.location.href);u.searchParams.set('term',term);history.replaceState({},'',u);render();};});
      document.querySelectorAll('[data-class-tab]').forEach(function(btn){btn.onclick=function(){document.querySelectorAll('[data-class-tab]').forEach(function(x){x.classList.toggle('active',x===btn);});renderTab(btn.dataset.classTab);};});
      renderTab('overview');
    }
    function renderTab(tab){
      var panel=document.getElementById('class-tab-panel'), ta=termAssignments(), avg=average(); if(!panel)return;
      if(tab==='overview'){
        var latest=ta.slice(0,4);
        panel.innerHTML='<div class="class-workspace-grid"><div>'+
          '<div class="class-mini-stat-grid"><div class="class-mini-stat"><span>Students</span><b>'+students.length+'</b></div><div class="class-mini-stat"><span>Assignments</span><b>'+ta.length+'</b></div><div class="class-mini-stat"><span>Class Average</span><b>'+(avg==null?'—':avg+'%')+'</b></div></div>'+
          '<div class="card"><div class="card-header"><div class="card-title">Class News & Activity</div></div><div class="card-body"><div class="class-feed">'+(latest.length?latest.map(function(a){return '<div class="class-feed-row"><div class="class-feed-icon"><i class="fa-solid fa-clipboard-list"></i></div><div class="class-feed-main"><div class="class-feed-title">'+SMS_UI.esc(a.title)+'</div><div class="class-feed-text">'+SMS_UI.esc(a.type)+' · '+a.totalPoints+' points</div></div><div class="class-feed-date">Due '+SMS_UI.fmtDate(a.dueDate)+'</div></div>';}).join(''):announcements.slice(0,3).map(function(a){return '<div class="class-feed-row"><div class="class-feed-icon"><i class="fa-solid fa-bullhorn"></i></div><div class="class-feed-main"><div class="class-feed-title">'+SMS_UI.esc(a.title)+'</div><div class="class-feed-text">'+SMS_UI.esc(a.body)+'</div></div><div class="class-feed-date">'+SMS_UI.fmtDate(a.date)+'</div></div>';}).join('')||'<div class="text-secondary fs-sm">No class activity for this semester yet.</div>')+'</div></div></div></div>'+
          '<aside class="class-side-stack"><div class="card"><div class="card-header"><div class="card-title">Teacher & Class Information</div></div><div class="card-body"><div style="display:flex;align-items:center;gap:10px;margin-bottom:14px">'+SMS_UI.avatarHtml(cls.teacherName||teacher.fullName)+'<div><div class="fw-700">'+SMS_UI.esc(cls.teacherName||teacher.fullName)+'</div><div class="fs-xs text-secondary">'+SMS_UI.esc(cls.subject||'Teacher')+'</div></div></div><div class="fs-sm text-secondary" style="line-height:1.7"><b style="color:var(--text-1)">Room:</b> '+SMS_UI.esc(cls.room||'—')+'<br><b style="color:var(--text-1)">Schedule:</b> '+SMS_UI.esc(cls.schedule||'—')+'<br><b style="color:var(--text-1)">Term:</b> '+SMS_UI.esc(termData()?termData().name:(term==='S2'?'Semester 2':'Semester 1'))+'</div></div></div>'+
          '<div class="card"><div class="card-header"><div class="card-title">Students <span class="text-secondary">('+students.length+')</span></div><button class="btn btn-sm btn-ghost" data-open-roster>View all</button></div><div class="card-body"><div class="class-roster-mini">'+students.slice(0,7).map(function(s){return '<div class="class-roster-person">'+SMS_UI.avatarHtml(s.fullName)+'<div class="person-main"><div class="person-name">'+SMS_UI.esc(s.fullName)+'</div><div class="person-meta">'+SMS_UI.esc(s.grade)+'</div></div></div>';}).join('')+'</div></div></div>'+
          '<div class="card"><div class="card-header"><div class="card-title">Quick Actions</div></div><div class="card-body" style="display:flex;gap:8px;flex-wrap:wrap">'+(canAttendance?'<a class="btn btn-sm btn-secondary" href="./attendance.html"><i class="fa-solid fa-clipboard-check"></i>Attendance</a>':'')+(canGrades?'<a class="btn btn-sm btn-secondary" href="./gradebook.html"><i class="fa-solid fa-file-pen"></i>Gradebook</a>':'')+'<a class="btn btn-sm btn-secondary" href="./assignments.html"><i class="fa-solid fa-list-check"></i>Assignments</a></div></div></aside></div>';
        var r=panel.querySelector('[data-open-roster]'); if(r)r.onclick=function(){document.querySelector('[data-class-tab="roster"]').click();};
      } else if(tab==='news'){
        var news=announcements.slice(0,6); panel.innerHTML='<div class="card"><div class="card-header"><div class="card-title">Class & School News</div><div class="card-subtitle">Updates visible while working in '+SMS_UI.esc(cls.name)+'</div></div><div class="card-body"><div class="class-feed">'+(news.length?news.map(function(a){return '<div class="class-feed-row"><div class="class-feed-icon"><i class="fa-solid fa-bullhorn"></i></div><div class="class-feed-main"><div class="class-feed-title">'+SMS_UI.esc(a.title)+'</div><div class="class-feed-text">'+SMS_UI.esc(a.body)+'</div></div><div class="class-feed-date">'+SMS_UI.fmtDate(a.date)+'</div></div>';}).join(''):'<div class="text-secondary fs-sm">No news posted.</div>')+'</div></div></div>';
      } else if(tab==='calendar'){
        panel.innerHTML='<div class="card"><div class="card-header"><div class="card-title">'+(term==='S2'?'Semester 2':'Semester 1')+' Class Calendar</div></div><div class="card-body"><div class="class-feed">'+(ta.length?ta.map(function(a){return '<div class="class-feed-row"><div class="class-feed-icon"><i class="fa-solid fa-calendar-day"></i></div><div class="class-feed-main"><div class="class-feed-title">'+SMS_UI.esc(a.title)+'</div><div class="class-feed-text">'+SMS_UI.esc(a.type)+' · '+a.totalPoints+' points</div></div><div class="class-feed-date">'+SMS_UI.fmtDate(a.dueDate)+'</div></div>';}).join(''):'<div class="text-secondary fs-sm">No class dates or assignments scheduled for this semester yet.</div>')+'</div></div></div>';
      } else if(tab==='documents'){
        panel.innerHTML='<div class="grid-2" style="gap:14px"><div class="card"><div class="card-body"><div style="display:flex;gap:12px"><div class="stat-icon blue"><i class="fa-solid fa-file-lines"></i></div><div><div class="fw-700">'+SMS_UI.esc(cls.name)+' Course Overview</div><div class="fs-xs text-secondary">Class information · '+SMS_UI.esc(cls.schedule||'Schedule pending')+'</div></div></div></div></div>'+docs.slice(0,5).map(function(d){return '<div class="card"><div class="card-body"><div style="display:flex;gap:12px"><div class="stat-icon red"><i class="fa-solid fa-file-pdf"></i></div><div style="min-width:0"><div class="fw-700">'+SMS_UI.esc(d.title)+'</div><div class="fs-xs text-secondary">'+SMS_UI.esc(d.category||'School document')+' · '+SMS_UI.fmtDate(d.uploadDate)+'</div></div></div></div></div>';}).join('')+'</div>';
      } else if(tab==='photos'){
        panel.innerHTML='<div class="class-photo-grid">'+(albums.length?albums.slice(0,6).map(function(a){return '<div class="class-photo-card" style="background:'+SMS_UI.esc(a.coverColor||'#334155')+'"><div class="class-photo-title">'+SMS_UI.esc(a.title)+'</div><div class="class-photo-meta">'+a.photoCount+' photos · '+SMS_UI.fmtDate(a.date)+'</div></div>';}).join(''):'<div class="text-secondary fs-sm">No school photo albums available.</div>')+'</div>';
      } else if(tab==='roster'){
        var cols=[{label:'Student',render:function(s){return '<div class="fw-700">'+SMS_UI.esc(s.fullName)+'</div><div class="fs-xs text-secondary">'+SMS_UI.esc(s.grade)+'</div>'; }},{label:'Status',render:function(s){return SMS_UI.statusBadge(s.status);} }];
        if(canGuardian)cols.push({label:'Guardian Contact',render:function(s){var p=SMS_PARENTS.find(function(x){return (s.parentIds||[]).includes(x.id);});return p?'<div class="fs-sm">'+SMS_UI.esc(p.legalName||p.fullName)+'</div><div class="fs-xs text-secondary">'+SMS_UI.esc(p.phone||p.email||'')+'</div>':'—';}});
        if(canHealth)cols.push({label:'Health Alert',render:function(s){var x=s.sensitiveInfo||{},items=(x.allergies||[]).concat(x.medicalConditions||[]);return items.length?SMS_UI.badge(items.join(', '),'warning'):'<span class="text-secondary fs-xs">None listed</span>';}});
        panel.innerHTML=SMS_UI.buildTable({columns:cols,rows:students,emptyTitle:'No students in this class'});
      }
    }
    render();
  });
})();
}
