if (SMS_TEACHER_LAYOUT.init("messages")) {
(function(){
  "use strict";
  var user=SMS_AUTH.getCurrentUser(),canSend=SMS_AUTH.hasTeacherPermission("messages.send");
  function load(){return SMS_API.getMessages(user.id).then(render);}
  function render(messages){
    document.getElementById('page-content').innerHTML=SMS_UI.pageHeader({title:'Messages',subtitle:canSend?'Communicate through approved school channels':'View messages from school administration',breadcrumb:['Teacher','Messages'],actions:canSend?[{label:'New Message',icon:'fa-pen',id:'new-msg-btn',primary:true}]:[]})+(!canSend?'<div class="alert alert-info" style="margin-bottom:16px"><i class="fa-solid fa-eye"></i><span>Messaging is <strong>View only</strong> for your account.</span></div>':'')+'<div id="msgs-list" style="display:flex;flex-direction:column;gap:10px"></div>';
    if(canSend)document.getElementById('new-msg-btn').addEventListener('click',openCompose);
    document.getElementById('msgs-list').innerHTML=messages.length?messages.map(function(m){var isFrom=m.fromUserId===user.id;return '<div class="card" style="border-left:3px solid '+(m.read?'var(--border-color)':'var(--color-primary)')+'" data-msg-id="'+m.id+'"><div class="card-body"><div style="display:flex;justify-content:space-between"><div><div class="fw-600 fs-sm">'+SMS_UI.esc(m.subject)+'</div><div class="fs-xs text-secondary">'+(isFrom?'To: '+SMS_UI.esc(m.toName):'From: '+SMS_UI.esc(m.fromName))+' · '+SMS_UI.fmtDateTime(m.date)+'</div></div>'+(!m.read&&!isFrom?SMS_UI.badge('New','primary'):'')+'</div><div class="text-secondary fs-sm" style="margin-top:8px">'+SMS_UI.esc(m.body)+'</div></div></div>';}).join(''):'<div class="card"><div class="card-body">'+SMS_UI.emptyState({icon:'fa-envelope',title:'No messages yet'})+'</div></div>';
    document.querySelectorAll('[data-msg-id]').forEach(function(el){el.addEventListener('click',function(){SMS_API.markMessageRead(el.getAttribute('data-msg-id'));});});
  }
  function openCompose(){var recipients=SMS_USERS.filter(function(u){return u.schoolId===user.schoolId&&u.id!==user.id&&(['school_admin','branch_admin','parent'].includes(u.role))&&(!u.branchId||u.branchId===user.branchId);});SMS_UI.openDialog('<div class="dialog-header"><div><div class="dialog-title">New Message</div><div class="dialog-subtitle">Only approved school/guardian recipients are shown</div></div><button class="dialog-close" data-close-dialog><i class="fa-solid fa-xmark"></i></button></div><div class="dialog-body"><div class="form-group"><label class="form-label">Recipient</label><select class="input" id="msg-to">'+recipients.map(function(r){return '<option value="'+r.id+'">'+SMS_UI.esc(r.displayName)+' · '+SMS_AUTH.roleBadge(r.role)+'</option>';}).join('')+'</select></div><div class="form-group"><label class="form-label">Subject</label><input class="input" id="msg-subject"></div><div class="form-group"><label class="form-label">Message</label><textarea class="input" rows="5" id="msg-body"></textarea></div></div><div class="dialog-footer"><button class="btn btn-secondary" data-close-dialog>Cancel</button><button class="btn btn-primary" id="send-msg">Send Message</button></div>');document.getElementById('send-msg').addEventListener('click',function(){var rid=document.getElementById('msg-to').value,r=recipients.find(function(x){return x.id===rid;}),subject=document.getElementById('msg-subject').value.trim(),body=document.getElementById('msg-body').value.trim();if(!r||!subject||!body){SMS_UI.toast('Missing information','Recipient, subject and message are required.','error');return;}SMS_API.sendMessage({fromUserId:user.id,fromName:user.displayName,toUserId:r.id,toName:r.displayName,subject:subject,body:body,branchId:user.branchId,schoolId:user.schoolId}).then(function(){SMS_UI.closeDialog();SMS_UI.toast('Message sent','','success');load();});});}
  load();
})();
}
