SMS_ADMIN_LAYOUT.init("admissions");
(function(){
  "use strict";
  var schoolId=SMS_AUTH.getSchoolId(), branchId=SMS_AUTH.getBranchId(), apps=[];
  function load(){return SMS_API.getApplications(SMS_AUTH.hasAllBranchAccess()?null:branchId).then(function(r){apps=(r||[]).filter(function(a){return a.schoolId===schoolId;});});}
  function render(){
    var c={New:0,Review:0,Testing:0,Accepted:0,Waitlisted:0,Denied:0,Enrolled:0};apps.forEach(function(a){c[a.status]=(c[a.status]||0)+1;});
    document.getElementById('page-content').innerHTML=SMS_UI.pageHeader({title:'Admissions',subtitle:'Manage applications from inquiry through enrollment.',breadcrumb:['Students & Families','Admissions'],actions:[{label:'New Application',icon:'fa-plus',id:'new-app',primary:true}]})+
    '<div class="stats-grid" style="margin-bottom:18px">'+SMS_UI.statCard({icon:'fa-inbox',label:'Open Applications',value:String((c.New||0)+(c.Review||0)+(c.Testing||0)),color:'blue'})+SMS_UI.statCard({icon:'fa-circle-check',label:'Accepted',value:String(c.Accepted||0),color:'green'})+SMS_UI.statCard({icon:'fa-user-check',label:'Enrolled',value:String(c.Enrolled||0),color:'purple'})+SMS_UI.statCard({icon:'fa-hourglass-half',label:'Waitlisted',value:String(c.Waitlisted||0),color:'orange'})+'</div>'+
    '<div class="card"><div class="card-header"><div><div class="card-title">Application Pipeline</div><div class="text-secondary fs-sm">Click an application to review or update it.</div></div><div><input class="input" id="app-search" placeholder="Search applications…" style="max-width:240px"></div></div><div class="card-body" id="app-table"></div></div>';
    document.getElementById('new-app').addEventListener('click',openNew);
    document.getElementById('app-search').addEventListener('input',renderTable);
    renderTable();
  }
  function renderTable(){
    var q=(document.getElementById('app-search')?.value||'').toLowerCase();
    var rows=apps.filter(function(a){return !q||[a.studentName,a.guardianName,a.guardianEmail,a.gradeRequested,a.status].join(' ').toLowerCase().includes(q);});
    var box=document.getElementById('app-table');
    box.innerHTML=SMS_UI.buildTable({rows:rows,emptyIcon:'fa-file-circle-plus',emptyTitle:'No applications found',columns:[
      {label:'Applicant',render:function(a){return '<div class="fw-700">'+SMS_UI.esc(a.studentName)+'</div><div class="fs-xs text-secondary">'+SMS_UI.esc(a.guardianName)+'</div>'; }},
      {label:'Grade',render:function(a){return SMS_UI.esc(a.gradeRequested)}},
      {label:'Submitted',render:function(a){return SMS_UI.fmtDate(a.submittedAt)}},
      {label:'Docs',render:function(a){return '<span class="fs-sm">'+Number(a.documents||0)+'</span>'}},
      {label:'Status',render:function(a){return status(a.status)}}
    ]});
    SMS_UI.wireTableClicks(box,rows,openReview);
  }
  function status(s){var map={New:'info',Review:'warning',Testing:'warning',Accepted:'success',Enrolled:'success',Waitlisted:'gray',Denied:'danger'};return SMS_UI.badge(s,map[s]||'gray');}
  function openNew(){
    var branchOptions=SMS_BRANCHES.filter(function(b){return b.schoolId===schoolId;}).map(function(b){return '<option value="'+b.id+'">'+SMS_UI.esc(b.name)+'</option>';}).join('');
    var grades=SMS_GRADES.map(function(g){return '<option>'+SMS_UI.esc(g.name)+'</option>';}).join('');
    SMS_UI.openDialog('<div class="dialog-header"><div><div class="dialog-title">New Application</div><div class="dialog-subtitle">Capture enough family information to convert directly into enrollment.</div></div><button class="dialog-close" data-close-dialog><i class="fa-solid fa-xmark"></i></button></div><div class="dialog-body"><div class="form-grid"><div class="form-group"><label class="form-label">Student legal name *</label><input class="input" id="a-name"></div><div class="form-group"><label class="form-label">Date of birth</label><input class="input" type="date" id="a-dob"></div></div><div class="form-grid"><div class="form-group"><label class="form-label">Requested grade *</label><select class="input" id="a-grade">'+grades+'</select></div><div class="form-group"><label class="form-label">Campus</label><select class="input" id="a-branch">'+branchOptions+'</select></div></div><div class="card" style="margin:10px 0"><div class="card-header"><div class="card-title">Primary Guardian</div></div><div class="card-body"><div class="form-grid"><div class="form-group"><label class="form-label">Full legal name *</label><input class="input" id="a-guardian"></div><div class="form-group"><label class="form-label">Relationship</label><select class="input" id="a-guardian-rel"><option>Mother</option><option>Father</option><option>Guardian</option><option>Other</option></select></div></div><div class="form-grid"><div class="form-group"><label class="form-label">Email *</label><input class="input" type="email" id="a-email"></div><div class="form-group"><label class="form-label">Phone</label><input class="input" id="a-phone"></div></div></div></div><div class="card" style="margin:10px 0"><div class="card-header"><div class="card-title">Home Address</div></div><div class="card-body"><div class="form-group"><label class="form-label">Street</label><input class="input" id="a-street"></div><div class="form-grid"><div class="form-group"><label class="form-label">City</label><input class="input" id="a-city"></div><div class="form-group"><label class="form-label">State</label><input class="input" id="a-state" value="TX"></div></div><div class="form-group"><label class="form-label">ZIP</label><input class="input" id="a-zip"></div></div></div><div class="form-group"><label class="form-label">Notes</label><textarea class="input" id="a-notes" rows="3"></textarea></div></div><div class="dialog-footer"><button class="btn btn-secondary" data-close-dialog>Cancel</button><button class="btn btn-primary" id="save-app">Add Application</button></div>',{xl:true});
    document.getElementById('save-app').addEventListener('click',function(){var name=document.getElementById('a-name').value.trim(),guardian=document.getElementById('a-guardian').value.trim(),email=document.getElementById('a-email').value.trim();if(!name||!guardian||!email){SMS_UI.toast('Missing information','Student, guardian, and email are required.','error');return;}SMS_API.createApplication({schoolId:schoolId,branchId:document.getElementById('a-branch').value,studentName:name,dateOfBirth:document.getElementById('a-dob').value,gradeRequested:document.getElementById('a-grade').value,guardianName:guardian,guardianEmail:email,guardianPhone:document.getElementById('a-phone').value.trim(),guardianRelationship:document.getElementById('a-guardian-rel').value,address:{street:document.getElementById('a-street').value.trim(),line2:'',city:document.getElementById('a-city').value.trim(),state:document.getElementById('a-state').value.trim(),zip:document.getElementById('a-zip').value.trim(),country:'United States'},notes:document.getElementById('a-notes').value}).then(function(){SMS_UI.closeDialog();SMS_UI.toast('Application added','','success');load().then(render);});});
  }
  function openReview(a){
    var opts=['New','Review','Testing','Accepted','Waitlisted','Denied','Enrolled'].map(function(x){return '<option '+(x===a.status?'selected':'')+'>'+x+'</option>';}).join('');
    SMS_UI.openDialog('<div class="dialog-header"><div><div class="dialog-title">'+SMS_UI.esc(a.studentName)+'</div><div class="dialog-subtitle">'+SMS_UI.esc(a.gradeRequested)+' · '+SMS_UI.esc(a.guardianName)+'</div></div><button class="dialog-close" data-close-dialog><i class="fa-solid fa-xmark"></i></button></div><div class="dialog-body"><div class="form-grid"><div class="form-group"><label class="form-label">Status</label><select class="input" id="review-status">'+opts+'</select></div><div class="form-group"><label class="form-label">Documents received</label><input class="input" type="number" min="0" id="review-docs" value="'+Number(a.documents||0)+'"></div></div><div class="form-group"><label class="form-label">Admissions notes</label><textarea class="input" rows="4" id="review-notes">'+SMS_UI.esc(a.notes||'')+'</textarea></div><div class="sy-callout" style="margin:0"><i class="fa-solid fa-circle-info"></i><div><strong>Enrollment conversion</strong><span>Once accepted, you can create the student profile here. The Supabase version will also create the guardian account and invitation.</span></div></div></div><div class="dialog-footer"><button class="btn btn-secondary" data-close-dialog>Cancel</button><button class="btn btn-secondary" id="save-review">Save</button>'+(a.status==='Accepted'?'<button class="btn btn-primary" id="convert-app"><i class="fa-solid fa-user-plus"></i> Enroll Student</button>':'')+'</div>',{lg:true});
    document.getElementById('save-review').addEventListener('click',function(){SMS_API.updateApplication(a.id,{status:document.getElementById('review-status').value,documents:Number(document.getElementById('review-docs').value||0),notes:document.getElementById('review-notes').value}).then(function(){SMS_UI.closeDialog();SMS_UI.toast('Application updated','','success');load().then(render);});});
    var convert=document.getElementById('convert-app');if(convert)convert.addEventListener('click',function(){var parts=a.studentName.trim().split(/\s+/),first=parts.shift(),last=parts.pop()||'Student',middle=parts.join(' '),gp=(a.guardianName||'Guardian').trim().split(/\s+/),gf=gp.shift(),gl=gp.pop()||'Guardian',gm=gp.join(' '),g=SMS_GRADES.find(function(x){return x.name===a.gradeRequested;})||SMS_GRADES[0],studentRecord=null;SMS_API.createStudent({schoolId:schoolId,branchId:a.branchId,firstName:first,middleName:middle,lastName:last,preferredName:first,grade:g.name,gradeId:g.id,gender:'',dateOfBirth:a.dateOfBirth||'',enrollmentDate:new Date().toISOString().slice(0,10),status:'Active',address:a.address||{}}).then(function(sr){studentRecord=sr.student;return SMS_API.createParent({schoolId:schoolId,branchId:a.branchId,firstName:gf,middleName:gm,lastName:gl,email:a.guardianEmail||'',phone:a.guardianPhone||'',relationship:a.guardianRelationship||'Guardian',childrenIds:[studentRecord.id],isPrimary:true,legalGuardian:true,authorizedPickup:true,receivesSchoolCommunication:true,address:a.address||{}});}).then(function(pr){return SMS_API.updateStudent(studentRecord.id,{parentIds:[pr.parent.id]});}).then(function(){return SMS_API.updateApplication(a.id,{status:'Enrolled'});}).then(function(){SMS_UI.closeDialog();SMS_UI.toast('Student enrolled',a.studentName+' and the primary guardian were added to the active records.','success');load().then(render);});});
  }
  load().then(render);
})();
